In [2]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

#Import CSV data as pandas Dataframe

In [7]:
df= pd.read_csv('raw.csv')

In [9]:
df.head(10)

,StudentID,Name,Age,Email,Department,GPA,GraduationYear
0,3336,David Palmer,19,sean43@hotmail.com,Mathematics,3.16,2026
1,8774,Andrew Roach,23,vbecker@harvey.com,Chemistry,3.75,2027
2,1396,Jonathan Gonzalez,22,hollydavis@gmail.com,Physics,2.95,2027
3,6716,Kenneth Morrow,24,ganderson@wheeler-atkins.info,Physics,3.55,2029
4,8830,Kaitlyn Martinez,18,hayesdiane@gmail.com,Chemistry,2.29,2025
5,5305,Tiffany Wolf,23,qanderson@taylor.com,Mathematics,3.30,2029
6,5048,James Reyes,20,drodriguez@nguyen-cooper.info,Chemistry,2.44,2029
7,5986,Samantha Sellers,20,michelle27@hubbard-webster.com,Mathematics,3.44,2025
8,8721,Michael Kim,25,jacksonhannah@miles.com,Computer Science,3.27,2027
9,6622,Emily Davis,18,george02@hotmail.com,Physics,3.09,2030

In [10]:
df.shape

(202, 7)

checking if any duplicate values in a dataset
##using df.isna()--> gives the whole data and write "True" for "null" values and "False" for "not null" values
##using df.isna().sum()--> gives the total null values in a dataset columnwise

In [12]:
df.isna().sum()

StudentID         0
Name              0
Age               0
Email             0
Department        0
GPA               0
GraduationYear    0
dtype: int64

checking duplicate values

In [13]:
df.duplicated().sum()

np.int64(2)

checking the types of values in a dataset

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 202 entries, 0 to 201
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   StudentID       202 non-null    int64
 1   Name            202 non-null    object
 2   Age             202 non-null    int64
 3   Email           202 non-null    object
 4   Department      202 non-null    object
 5   GPA             202 non-null    float64
 6   GraduationYear  202 non-null    int64
dtypes: float64(1), int64(3), object(3)
memory usage: 11.2+ KB

checking the number of unique values of each column

In [15]:
df.nunique()

StudentID         200
Name              200
Age                 8
Email             200
Department          5
GPA               133
GraduationYear      7
dtype: int64

statistics of dataset

In [16]:
df.describe()

         StudentID         Age         GPA  GraduationYear
count   202.000000  202.000000  202.000000      202.000000
mean   5730.930693   21.564356    3.029059     2027.188119
std    2495.304290    2.261140    0.588297        2.003543
min    1066.000000   18.000000    2.000000     2024.000000
25%    3700.250000   20.000000    2.532500     2025.000000
50%    5664.000000   22.000000    3.100000     2027.000000
75%    8015.250000   23.750000    3.507500     2029.000000
max    9985.000000   25.000000    3.990000     2030.000000

In [17]:
df.head()

,StudentID,Name,Age,Email,Department,GPA,GraduationYear
0,3336,David Palmer,19,sean43@hotmail.com,Mathematics,3.16,2026
1,8774,Andrew Roach,23,vbecker@harvey.com,Chemistry,3.75,2027
2,1396,Jonathan Gonzalez,22,hollydavis@gmail.com,Physics,2.95,2027
3,6716,Kenneth Morrow,24,ganderson@wheeler-atkins.info,Physics,3.55,2029
4,8830,Kaitlyn Martinez,18,hayesdiane@gmail.com,Chemistry,2.29,2025

checking the categories of each column in a datset

In [18]:
print("Checking the categories in 'GPA' category: ", df['GPA'].unique())

Checking the categories in 'GPA' category:  [3.16 3.75 2.95 3.55 2.29 3.3  2.44 3.44 3.27 3.09 3.42 2.33 3.76 2.02
 3.35 3.21 3.92 3.43 2.05 3.68 3.84 3.82 2.99 2.49 3.56 3.58 2.82 2.98
 2.15 2.73 2.92 3.51 2.75 3.26 3.74 2.37 2.67 2.7  3.5  3.6  3.47 3.05
 3.06 3.94 2.13 3.64 2.81 2.94 3.8  2.62 2.1  2.39 3.29 2.79 2.47 3.88
 2.18 3.18 3.46 2.87 2.53 3.23 2.6  2.83 2.74 3.67 3.28 3.97 3.07 2.14
 3.52 2.84 3.86 2.3  3.77 3.39 3.2  3.95 2.11 2.76 3.   2.85 3.37 3.41
 2.86 2.51 2.38 3.25 2.2  2.77 2.48 3.63 3.03 3.65 3.32 2.41 2.9  3.72
 2.04 2.08 2.5  3.98 3.85 3.19 2.03 2.55 2.71 3.99 3.78 3.71 2.59 2.78
 2.45 2.58 3.14 3.59 2.22 3.12 2.54 2.01 2.09 3.11 2.   3.9  2.63 2.61
 3.96 2.34 2.24 2.06 2.17 2.57 3.15]

In [22]:
#define numerical and categorical features in a dataset
numerical_features=[feature for feature in df.columns if df[feature].dtype!="O"]
categorical_features=[feature for feature in df.columns if df[feature].dtype=="O"]

#printing the numerical and categorical features
print(f"we have {len(numerical_features)} numerical features in a dataset: {numerical_features}")
print(f"we have {len(categorical_features)} categorical features in a dataset: {categorical_features}")

we have 4 numerical features in a dataset: ['StudentID', 'Age', 'GPA', 'GraduationYear']
we have 3 categorical features in a dataset: ['Name', 'Email', 'Department']

In [ ]:
"I"